;; My configuration that doesn't depend on any variable
;; This file is loaded by emacs.el, which is generated by default.nix

;; Enable the solarised theme, with dark background
(setq frame-background-mode 'dark)
(load-theme 'solarized t)
(enable-theme 'solarized)
